name = "Better vanilla"
author = "TheHolyTachanka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f50ac3229697200e4943ff9553d7cd2da6e4472409bc0234e6659bf37893da5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
