name = "Better vanilla"
author = "TheHolyTachanka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74f954614e6500fa72ce14c3d432f859e2b5c085bc59f939410dd2eceacf0b52"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
