name = "Better vanilla"
author = "TheHolyTachanka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a354aa3c2b19f989316f5e9430d027bcc7a7e9984145374558535badf3a6e78c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
