name = "Better vanilla"
author = "TheHolyTachanka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ee0d1f63fa6476cc0a9291db2dbf317fabac3a04646a8bc9eac417f426cca5a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
