name = "Better vanilla"
author = "TheHolyTachanka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aecccd0b5c44e7c0202a4348e34ad605bfa5373f9d96df6fbb3d53b824c42dec"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
